- HALO-segmentation-notes.md
- scripts/requirements.txt
> Fix some initial problems

- HALO-segmentation-notes.md
Dear all! I included the naming conventions we agreed on in our meeting on Tuesday into the segmentation notes. If you have any suggestions or additions, please add them!
> Adding information and naming conventions agreed on during our meeting at 20240917

- HALO-segmentation-notes.md
> Update naming convention

- scripts/navdata.py
We now have all position altitude datasets in IPFS, thus, the data shouldn't change anymore and we can use a constant versions of the data. This would also allow to pin this CID and have fully offline access to the data.
> navdata: set fixed position_altitude CID

- scripts/utils.py
Some functions were missing module imports. Sorry for not testing properly earlier!
> corrent missing imports

- scripts/segmentation_template.md
- scripts/utils.py
This PR adds next to the segments also a list of `events` and loads and plots the EC track in the template.
> Add events and ec track

- scripts/segmentation_template.md
This PR adds a section to the end of the template that can be used for a quick check of the YAML file. 
* loads the written YAML file from disk
* plots the "straight_leg" and "circle" segments"
* plots for each circle the a full circle with the approximated circle radius to check whether the algorithm results in reasonable radii independen tof possible deviations from the circle track
> template: test loading yaml and plotting segments and circle radii

- scripts/segmentation_template.md
Reverts orcestra-campaign/flight_segmentation#83
I'd like to revert the revert of the original PR #79 as to me this still seems to be a useful feature :)
> Revert "Revert "template: test loading yaml and plotting segments and circle radii""

- scripts/navdata.py
- scripts/utils.py
for the derivation of closest overpass over a point (measurement site), the distance will be more accurate if the high resolution BAHAMAS data is used. I therefore enabled the latter in `navdata` and added an independent improvement in the plotting function of track and target location.
> Improve overpass plot and enable highres HALO data

- scripts/segmentation_HALO-20240912a.md
Just added the yaml import and tests from the template to the segmentation markdown file in which they hadn't been included before.
> Add template updates to segmentation markdown

- .github/workflows/compile.yaml
- .gitignore
- Makefile
- scripts/index.py
- scripts/report.py
- scripts/templates/index.html
Not sure, if this is still of any interest, but this PR would add the generation of HTML reports to the CI pipeline and would create a very basic index file, which mainly just points to the generated report files.
> Add reports to CI

- scripts/segmentation_HALO-20240825a.md
Segmentation ready for review.
> Segmentation of flight HALO-20240825a

- scripts/segmentation_HALO-20240909a.md
Between the second circle and the EC track there is a small "climbing circle" that I am unsure how to best label. Should it have the attribute `circle`?
> Segmentation of flight HALO-20240909a

- scripts/segmentation_HALO-20240929a.md
Ready for review. Closes issue #40 (transfer flight from Barbados to Memmingen without EC underpass and without drop sonde launches).
> Segmentation of flight HALO-20240929a

- scripts/segmentation_HALO-20240829a.md
Segmentation ready for review.
> Segmentation of flight HALO-20240829a

- scripts/segmentation_HALO-20240831a.md
Ready to be merged - review already finished.
> Segmentation for flight HALO-20240831a

- scripts/report.py
- scripts/segmentation_HALO-20240809b.md
- scripts/segmentation_HALO-20240811a.md
- scripts/segmentation_HALO-20240816a.md
- scripts/segmentation_HALO-20240818a.md
- scripts/segmentation_HALO-20240821a.md
- scripts/segmentation_HALO-20240822a.md
- scripts/segmentation_HALO-20240825a.md
- scripts/segmentation_HALO-20240829a.md
- scripts/segmentation_HALO-20240831a.md
- scripts/segmentation_HALO-20240903a.md
- scripts/segmentation_HALO-20240906a.md
- scripts/segmentation_HALO-20240909a.md
- scripts/segmentation_HALO-20240912a.md
- scripts/segmentation_HALO-20240914a.md
- scripts/segmentation_HALO-20240916a.md
- scripts/segmentation_HALO-20240919a.md
- scripts/segmentation_HALO-20240921a.md
- scripts/segmentation_HALO-20240924a.md
- scripts/segmentation_HALO-20240926a.md
- scripts/segmentation_HALO-20240929a.md
- scripts/segmentation_template.md
Fix pipeline by adding:
* longer nb execution time
* fix l1 dropsonde function in reports.py which crashed for empty dropsonde files
> Fix pipeline

- scripts/segmentation_HALO-20240907a.md
- scripts/utils.py
Segments are ready to be reviewed. Pull request as "draft" because the wrong EC track was plotted and, hence, the EC event could not be determined correctly.
> Segmentation of flight HALO-20240907a 

- scripts/segmentation_HALO-20240827a.md
Some weird behaviour of Meteor overpass calculation still needs to be understood (perhaps together during review) but otherwise, this segmentation is ready for review.
> Segmentation of flight HALO-20240827a

- scripts/checkers.py
- scripts/report.py
- scripts/templates/flight.html
This PR updates the HTML reports on two points:
* the former `irregularities` and `comments` statements are combined in the currently used `remarks`
* the dropsonde flag was renamed from `UNKNOWN` to `ALL_FLAGS`. This is just a wording thing, but I like it better :)
> Update html reports

- scripts/segmentation_HALO-20240813a.md
This PR only touches HALO-20240813 which has the problem that the quality controlled 100Hz BAHAMAS data is missing for the last 40min of the flight. To get a reasonable landing time, I appended the 100Hz data with the quicklook (QL) BAHAMAS data which is lacking quality control, but seems good enough for defining the landing time. I would refrain from defining additional segments during those last 40min as roll angle etc are not quality controlled and not corrected for potential errors.
As this flight is the only one with missing data **and** QL data being available, I'd only add the respective code within the notebook. 
This PR closes issues #128 and #153.
> HALO-20240813a: fix landing time
