orcestra-campaign/flight_segmentation

- scripts/environment.yaml
Adding pip to dependencies before using it to specify further requirements mutes a warning that otherwise pops up.
> Add pip to dependencies in environment.yaml

- HALO-segmentation-notes.md
Circle segments are supposed to include all sondes associated with the circle, even if this means that the roll angle or other variables of the aircraft's state are out of their nominal circle range.
> Update definition of circle segment

- scripts/segmentation_template.md
I added a couple of small convenient features and replace some code by a function that @tmieslinger had already put in utils.py:
- added interactive plot for aircraft heading
- computed takeoff, landing, and duration using the respective utils function
- added a section where individual segments can be plotted in read on top of the full track which helped me visually identify the straight_leg segments which lie on the EC track (not always clear from the zoomed-in plots)
> add a few convenient features to template

- scripts/utils.py
On some days, there were no satellite track forecasts issued, and those days can be flight days. An exemplary day is 20240818. For those days, the function `get_ec_track(flight_id, ds)` did threw an error so far. To avoid this, I added a `try...except` statement: In case that there is no satellite track forecast for the flight day available that has been issued on the same day, the function will now automatically use an older forecast which was issued closest to the flight day. To inform the user in this case, it will also throw a warning message.
> Handle flightdays on which no satellite track forecast was issued

- scripts/segmentation_template.md
Since loading the PACE track data takes quite long, it should be avoided for flights which didn't had a PACE coordination, which were most of the flights. However, if the PACE track is not loaded, cells in which it should be plotted throw an error message. This pull request adds some code to avoid that.
> Advanced handling of PACE tracks

- scripts/utils.py
The transfer flights start and end at a different airport, thus the current way of determining the takeoff and landing time in `get_takeoff_landing()` doesn't work for them. This PR distinguishes between takeoff and landing airports and adds the Memmingen airport to enable a reliable estimation of takeoff and landing for the transfer flights.
> Adjustments in get_takeoff_landing() necessary for transfer flights

- scripts/utils.py
In some flights there were multiple overpasses of the same reference point (i.e., Meteor, BCO or CVAO). One example is flight HALO-20240903a, which overpassed Meteor twice. However, the functions `meteor_events()` and `target_event()` were designed for only one overpass of a reference point per flight as they determined the closest meeting point of the entire flight. With this PR one can now also pass the flight segment as an argument to those two functions. In case a flight segment is given, the function will now determine the closest meeting point for that segment. If no segment is given, the functions work as before and find the closest meeting point of the whole flight.
> Add possibility to find meeting point of HALO and Meteor, BCO or CV in a user-defined segment

- scripts/utils.py
For some flights, loading dropsonde data results in an error because the ipfs folder contains empty files. The additional code snipped (thanks to @lkluft !) tells `get_sondes_l1` to skip these empty files and enables a smooth loading of the good data.
> skip empty dropsonde files

- scripts/utils.py
The function to determine takeoff and landing is called in several subfunctions. A print statement within the function seems fine for the debugging, but I'd remove it for general usage.
> remove print statements for takeoff and landing

- scripts/navdata.py
This change updates to the latest HALO navdata:
```bash
$ ipfs resolve /ipns/latest.orcestra-campaign.org/products/HALO/position_attitude
/ipfs/QmTGwJ6VAn2FTiwsXaAA4BUA82RN2zQPBEJ8rpWrviW4c3
```
The change mainly adds new flights to the navdata:
```bash
$ diff <(ipfs ls /ipfs/QmP1ragFLB3jbjBj9tU3piitkADPqBUjqgydhcFjFGXrii) <(ipfs ls  /ipfs/QmTGwJ6VAn2FTiwsXaAA4BUA82RN2zQPBEJ8rpWrviW4c3)
9c9
< QmSTkGdQLFvzYWdtypSAkfecTkFo3cJJqWkadwR86TU51y - HALO-20240827a.zarr/
---
> QmUEnPiFXTXqmFo9jsKCyJSGgybrUrSrN2jUnLyZJ7zGCJ - HALO-20240827a.zarr/
24a25,32
> QmZGJbaQvAWppqV9npjxNfLTXtwp3xwneVQDZRpEevAj6F - HALO-20240929a.zarr/
> Qmd8seke5o9Ss5ao4me7cGdPDab7AEFrB1ujExstcGm62C - HALO-20241105a.zarr/
> QmWHdyo2ZQ84VcVhdrRBzy2Etyt3rg2y3PDonCfToJYamw - HALO-20241107a.zarr/
> …
```
> Update navdata CID

- scripts/utils.py
this PR fixes the dropsonde issue in flight 20240928a (#96) where dropsonde times were not monotonically increasing and selecting the segment time slices resulted in a kryptic error. However, the way we use the L1 dropsonde data assumes that they are sorted in time which we did not explicitly do so far. This PR adds a sort statement in the function that loads and concatenates the dropsonde L1 launch times.
> fix utils: sort dropsonde times to result in monotonic array

- scripts/report.py
- scripts/utils.py
This fixes the rare case where other files (e.g. `.DS_Store`) are included in a directory.
> Only iterate over NetCDF files

- .github/workflows/compile.yaml
The PR was broken 😬, it tried to use a feature intended for job steps on a whole job. This change should correct the problem.
* Reverts orcestra-campaign/flight_segmentation#142
* replaces `always()` by `success()`
> fix, CI: deploy only if build was successful

- .github/workflows/compile.yaml
testing whether removing the async execution of notebooks is still fast enough for our purpose to circumvent the problem of ZMQError stated in issue #144
> Remove parallel execution of nb in compile.yaml

- scripts/segmentation_HALO-20240811a.md
- scripts/segmentation_HALO-20240813a.md
- scripts/segmentation_HALO-20240816a.md
- scripts/segmentation_HALO-20240818a.md
- scripts/segmentation_HALO-20240821a.md
- scripts/segmentation_HALO-20240822a.md
- scripts/segmentation_HALO-20240825a.md
- scripts/segmentation_HALO-20240827a.md
- scripts/segmentation_HALO-20240829a.md
- scripts/segmentation_HALO-20240831a.md
- scripts/segmentation_HALO-20240903a.md
- scripts/segmentation_HALO-20240906a.md
- scripts/segmentation_HALO-20240907a.md
- scripts/segmentation_HALO-20240909a.md
- scripts/segmentation_HALO-20240912a.md
- scripts/segmentation_HALO-20240914a.md
- scripts/segmentation_HALO-20240916a.md
- scripts/segmentation_HALO-20240919a.md
- scripts/segmentation_HALO-20240921a.md
- scripts/segmentation_HALO-20240923a.md
- scripts/segmentation_HALO-20240924a.md
- scripts/segmentation_HALO-20240926a.md
- scripts/segmentation_HALO-20240928a.md
I added an additional kind "circle_clockwise" or "circle_counterclockwise" to each circle in all flights. There was one case in HALO-20240916a where a circle was split into two half-circles with opposite circle direction. In this case, I added both directions flags to kinds and left a note in the irregularity remark that already existed in the segment.
This PR closes #101
> add circle direction as kind in all flights

- scripts/utils.py
To determine takeoff/landing times for the November flights, I added the Oberpfaffenhofen airport (OP) altitude to the `get_takeoff_landing` function and made some further changes to the criteria for takeoff and landing times. The new version:
- can handle flights that take takeoff and land in OP
- can handle flights that take off in Memmingen and land in OP (those that have a "b" in their flight id)
- defines the landing time as the first instance after takeoff at which the plane reaches the airport altitude (rather than the last instance at which it is above the airport altitude)
The last modification was necessary because HALO experienced rather large bumps after touchdown in OP so that the previous algorithm consistently determined a too late landing time.
> Add op airport to get_takeoff_landing()

- README.md
- scripts/utils.py
For the November flights, I added the target `MIM` and its coordinates to the `target_event` function. The MIM was one of the ground stations that were deliberately overpassed by HALO.
> Add Meteorologisches Institut Muenchen (MIM) to target_event function

- scripts/report.py
- scripts/segmentation_HALO-20240811a.md
- scripts/segmentation_HALO-20240813a.md
- scripts/segmentation_HALO-20240816a.md
- scripts/segmentation_HALO-20240818a.md
- scripts/segmentation_HALO-20240821a.md
- scripts/segmentation_HALO-20240822a.md
- scripts/segmentation_HALO-20240825a.md
- scripts/segmentation_HALO-20240827a.md
- scripts/segmentation_HALO-20240829a.md
- scripts/segmentation_HALO-20240831a.md
- scripts/segmentation_HALO-20240903a.md
- scripts/segmentation_HALO-20240906a.md
- scripts/segmentation_HALO-20240907a.md
- scripts/segmentation_HALO-20240909a.md
- scripts/segmentation_HALO-20240912a.md
- scripts/segmentation_HALO-20240914a.md
- scripts/segmentation_HALO-20240916a.md
- scripts/segmentation_HALO-20240919a.md
- scripts/segmentation_HALO-20240921a.md
- scripts/segmentation_HALO-20240923a.md
- scripts/segmentation_HALO-20240924a.md
- scripts/segmentation_HALO-20240926a.md
- scripts/segmentation_HALO-20240928a.md
- scripts/segmentation_template.md
- scripts/utils.py
The flight segmentation is partly based on dropsonde data. The dropsonde datasets have been updated such that we decided to use the Level 2 dropsonde data with unique sonde identifiers for the flight segmentation. This PR updates the function for getting dropsonde data to read Level 2 data from IPFS. The flight notebooks are adapted to reflect the new function name `get_sondes_l2` and the reports are adjusted as well to the new dropsonde info.
> Update drop l2

- README.md
Allison pointed out that some segments with the `meteor_coordination` tag (mostly `straight_leg` segments) are so long, that HALO and Meteor were only close for a relatively short amount of time. In the long run, we might consider refining the definition of `meteor_coordination` as outlined in issue #169 but for the time being, I added a precautionary comment in the definition of `meteor_event` in the readme so users are aware of the need of further subsampling for their analysis.
> add precautionary comment to meteor_coordination

- scripts/segmentation_HALO-20240831a.md
@allison-wing pointed out that the circle segment `HALO-20240831a_33ff` was missing the tag for `meteor_coordination`. This PR adds the respective tag. METEOR was situated in the northern part of the circle and SEA-POL nicely covered the circle area with its scans :) Thanks Allison for the correction!!
> add missing meteor_coordination tag on 0831
